run:
  timeout: 5m
  concurrency: 4
  allow-parallel-runners: false
  modules-download-mode: mod
  tests: false
  go: "1.26.1"
usetesting.os-setenv: true
linters:
  disable-all: true
  fast: false
  enable:
    - bidichk
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varnamelen
    - whitespace
    - wsl
  # run:
  #   skip-files:
  #     - ".*_test.go$"

linters-settings:
  lll:
    line-length: 120
  funlen:
    lines: 75
    statements: 60
  goconst:
    min-len: 4
    ignore-tests: true
  whitespace:
    multi-func: false
    multi-if: true
  gocyclo:
    min-complexity: 50
  cyclop:
    skip-tests: true
    max-complexity: 15
  dogsled:
    max-blank-identifiers: 2
  errorlint:
    errorf: true
  godot:
    period: true
    capital: true
  nestif:
    min-complexity: 6
  gci:
    skip-generated: true
  gocognit:
    min-complexity: 30
  varnamelen:
    min-name-length: 2
    check-return: true
  revive:
    severity: warning
    rules:
      - name: atomic
      - name: confusing-naming
      - name: duplicated-imports

issues:
  exclude-dirs:
    - mocks
  max-issues-per-linter: 50
  max-same-issues: 3
